#!/usr/bin/env perl

# ----------------------------------------------------------------------
# runRunPlot
#
# run runPlot for a variety of settings
# ----------------------------------------------------------------------

use Getopt::Std;
getopts('df:m:');

my $ptlo = 400; 
if ($opt_f) {
    print "resetting ptlo = $opt_f.\n";
    $ptlo = $opt_f;
}


if ($opt_m eq "allNumbers") {
    &runAllNumbers(); 
}

exit(0); 


# ----------------------------------------------------------------------
sub runAllNumbers() {
    my @G0PT = (80, 120, 160); 

    # bin/runPlot -s 1 -c "PTLO=400;PTHI=10000;G0PT=100;g1PT=40" -n 20

    my $idx = 10*$ptlo; 
    my $command = "bin/runPlot -n 200"; 
    my $cuts = ""; 
    for ($g0pt = 0; $g0pt < $#G0PT; $g0pt++) {
	for ($g1pt = 60; $g1pt < $G0PT[$g0pt]; $g1pt += 20) {
	    $cuts = "PTLO=$ptlo;PTHI=10000;G0PT=$G0PT[$g0pt];g1PT=$g1pt";
	    $completeCommand = $command . " -c \"$cuts\" " . " -s $idx";
	    print "$completeCommand\n";
	    if (!$opt_d) {
		system("$completeCommand");
	    }
	    $idx++; 
	}
    }
}
