#!/usr/bin/env perl

# ----------------------------------------------------------------------
# runRunPlot
#
# run runPlot for a variety of settings
# ----------------------------------------------------------------------

use Getopt::Std;
getopts('df:m:');

my $ptlo = 400; 
if ($opt_f) {
    print "resetting ptlo = $opt_f.\n";
    $ptlo = $opt_f;
}


if ($opt_m eq "allNumbers") {
    &runAllNumbers(); 
}

exit(0); 


# ----------------------------------------------------------------------
sub runAllNumbers() {
    my @G0PT = (80, 120, 160, 200, 240); 

    my $idx = 10*$ptlo; 
    my $command = "bin/runPlot -n 1000"; 
    my $cuts = ""; 
    for ($g0pt = 0; $g0pt < $#G0PT; $g0pt++) {
	for ($g1pt = 50; $g1pt < $G0PT[$g0pt]; $g1pt += 20) {
	    $cuts = "PTLO=$ptlo,G0PT=$G0PT[$g0pt],G1PT=$g1pt";
	    $completeCommand = $command . " -c \"$cuts\" " . " -s $idx";
	    print "$completeCommand  >& $idx.log\n";
	    if (!$opt_d) {
		system("$completeCommand >& $idx.log");
	    }
	    $idx++; 
	}
    }
}
