#!/usr/bin/env perl
#
# ----------------------------------------------------------------------
#
# t3ui16>./merge -r h/ana/v7/mcatnlo_sys1 -o /scratch/ursl/h/
#
# Note: when merging a dataset with a new name, you MUST insert this into %jobs
#
# History   2013/10/21 first shot
#           2014/06/17 fixed shortcomings which I don't understand (grep problems ...)
#
# Send all questions, wishes and complaints to the 
#
# Author    Urs Langenegger <urs.langenegger@psi.ch>
# ----------------------------------------------------------------------
use lib '/shome/ursl/perl/modules/Tie-IxHash-1.23/lib';
use Tie::IxHash;

use Getopt::Std;
getopts('do:r:s:');


# -- more definitions
my $user  = $ENV{'USER'};

my $crash = ""; 

my $srmcmd  = "lcg-cp  -b -D srmv2";
my $dcap    = "dcap://t3se01.psi.ch:22125/pnfs/psi.ch/cms/trivcat";
my $srm     = "srm://t3se01.psi.ch:8443/srm/managerv2\\?SFN=/pnfs/psi.ch/cms/trivcat/store";
my $rootdir = "h/ana/v3";
if ($opt_r) {
    $rootdir = $opt_r; 
}
my $storage = "$srm/user/$user/$rootdir";

if (!$opt_o) {
    $opt_o = "."; 
}


# ----------------------------------------------------------------------
# -- The hash shall not change the order of its elements
tie %jobs, "Tie::IxHash";

%jobs = (
    "mcatnlo_is_150" => "cmcatnlo_150_chain", 
    "mcatnlo_is_151" => "cmcatnlo_151_chain", 
    "mcatnlo_is_155" => "cmcatnlo_155_chain", 
#
    "mcatnlo_150" => "cmcatnlo_v5_150_chain", 
    "mcatnlo_151" => "cmcatnlo_v5_151_chain", 
    "mcatnlo_155" => "cmcatnlo_v5_155_chain", 
    "mcatnlo_160" => "cmcatnlo_v5_160_chain", 
    "mcatnlo_161" => "cmcatnlo_v5_161_chain", 
    "mcatnlo_165" => "cmcatnlo_v5_165_chain", 
    "mcatnlo_170" => "cmcatnlo_v5_170_chain", 
    "mcatnlo_171" => "cmcatnlo_v5_171_chain", 
    "mcatnlo_175" => "cmcatnlo_v5_175_chain", 
    "mcatnlo_180" => "cmcatnlo_v5_180_chain", 
    "mcatnlo_181" => "cmcatnlo_v5_181_chain", 
    "mcatnlo_185" => "cmcatnlo_v5_185_chain", 
#
    "mcatnlo_200" => "cmcatnlo_v5_200_chain", 
    "mcatnlo_201" => "cmcatnlo_v5_201_chain", 
    "mcatnlo_205" => "cmcatnlo_v5_205_chain", 
    "mcatnlo_210" => "cmcatnlo_v5_210_chain", 
    "mcatnlo_211" => "cmcatnlo_v5_211_chain", 
    "mcatnlo_215" => "cmcatnlo_v5_215_chain", 
#
    "mcatnlo_400" => "cmcatnlo_v5_400_chain", 
    "mcatnlo_401" => "cmcatnlo_v5_401_chain", 
    "mcatnlo_405" => "cmcatnlo_v5_405_chain", 
    "mcatnlo_410" => "cmcatnlo_v5_410_chain", 
    "mcatnlo_411" => "cmcatnlo_v5_411_chain", 
    "mcatnlo_415" => "cmcatnlo_v5_415_chain", 
    "mcatnlo_420" => "cmcatnlo_v5_420_chain", 
    "mcatnlo_421" => "cmcatnlo_v5_421_chain", 
    "mcatnlo_425" => "cmcatnlo_v5_425_chain", 
#
    "mcatnlo_500" => "cmcatnlo_v5_500_chain", 
    "mcatnlo_501" => "cmcatnlo_v5_501_chain", 
    "mcatnlo_505" => "cmcatnlo_v5_505_chain", 
    "mcatnlo_510" => "cmcatnlo_v5_510_chain", 
    "mcatnlo_511" => "cmcatnlo_v5_511_chain", 
    "mcatnlo_515" => "cmcatnlo_v5_515_chain", 
    "mcatnlo_520" => "cmcatnlo_v5_520_chain", 
    "mcatnlo_521" => "cmcatnlo_v5_521_chain", 
    "mcatnlo_525" => "cmcatnlo_v5_525_chain", 
    "mcatnlo_530" => "cmcatnlo_v5_530_chain", 
    "mcatnlo_531" => "cmcatnlo_v5_531_chain", 
    "mcatnlo_535" => "cmcatnlo_v5_535_chain", 
#    "mcatnlo_540" => "cmcatnlo_v5_540_chain", 
#    "mcatnlo_541" => "cmcatnlo_v5_541_chain", 
#    "mcatnlo_545" => "cmcatnlo_v5_545_chain", 
#    "mcatnlo_550" => "cmcatnlo_v5_550_chain", 
#    "mcatnlo_551" => "cmcatnlo_v5_551_chain", 
#    "mcatnlo_555" => "cmcatnlo_v5_555_chain", 
#    "mcatnlo_560" => "cmcatnlo_v5_560_chain", 
#    "mcatnlo_561" => "cmcatnlo_v5_561_chain", 
#    "mcatnlo_565" => "cmcatnlo_v5_565_chain", 
#    "mcatnlo_570" => "cmcatnlo_v5_570_chain", 
#    "mcatnlo_571" => "cmcatnlo_v5_571_chain", 
#    "mcatnlo_575" => "cmcatnlo_v5_575_chain", 
#
    "mcatnlo_600" => "cmcatnlo_v5_600_chain", 
    "mcatnlo_601" => "cmcatnlo_v5_601_chain", 
    "mcatnlo_605" => "cmcatnlo_v5_605_chain", 
    "mcatnlo_610" => "cmcatnlo_v5_610_chain", 
    "mcatnlo_611" => "cmcatnlo_v5_611_chain", 
    "mcatnlo_615" => "cmcatnlo_v5_615_chain", 
    "mcatnlo_620" => "cmcatnlo_v5_620_chain", 
    "mcatnlo_621" => "cmcatnlo_v5_621_chain", 
    "mcatnlo_625" => "cmcatnlo_v5_625_chain", 
    "mcatnlo_630" => "cmcatnlo_v5_630_chain", 
    "mcatnlo_631" => "cmcatnlo_v5_631_chain", 
    "mcatnlo_635" => "cmcatnlo_v5_635_chain", 
    "mcatnlo_640" => "cmcatnlo_v5_640_chain", 
    "mcatnlo_641" => "cmcatnlo_v5_641_chain", 
    "mcatnlo_645" => "cmcatnlo_v5_645_chain", 
    "mcatnlo_650" => "cmcatnlo_v5_650_chain", 
    "mcatnlo_651" => "cmcatnlo_v5_651_chain", 
    "mcatnlo_655" => "cmcatnlo_v5_655_chain", 
    "mcatnlo_660" => "cmcatnlo_v5_660_chain", 
    "mcatnlo_661" => "cmcatnlo_v5_661_chain", 
    "mcatnlo_665" => "cmcatnlo_v5_665_chain", 
    "mcatnlo_670" => "cmcatnlo_v5_670_chain", 
    "mcatnlo_671" => "cmcatnlo_v5_671_chain", 
    "mcatnlo_675" => "cmcatnlo_v5_675_chain", 
    "mcatnlo_680" => "cmcatnlo_v5_680_chain", 
    "mcatnlo_681" => "cmcatnlo_v5_681_chain", 
    "mcatnlo_685" => "cmcatnlo_v5_685_chain", 
#
    "mcatnlo_7000" => "cmcatnlo_v5_7000_chain", 
    "mcatnlo_7001" => "cmcatnlo_v5_7001_chain", 
    "mcatnlo_7005" => "cmcatnlo_v5_7005_chain", 
    "mcatnlo_7010" => "cmcatnlo_v5_7010_chain", 
    "mcatnlo_7011" => "cmcatnlo_v5_7011_chain", 
    "mcatnlo_7015" => "cmcatnlo_v5_7015_chain", 
    "mcatnlo_7020" => "cmcatnlo_v5_7020_chain", 
    "mcatnlo_7021" => "cmcatnlo_v5_7021_chain", 
    "mcatnlo_7025" => "cmcatnlo_v5_7025_chain", 
    "mcatnlo_7030" => "cmcatnlo_v5_7030_chain", 
    "mcatnlo_7031" => "cmcatnlo_v5_7031_chain", 
    "mcatnlo_7035" => "cmcatnlo_v5_7035_chain", 
    "mcatnlo_7040" => "cmcatnlo_v5_7040_chain", 
    "mcatnlo_7041" => "cmcatnlo_v5_7041_chain", 
    "mcatnlo_7045" => "cmcatnlo_v5_7045_chain", 
    "mcatnlo_7050" => "cmcatnlo_v5_7050_chain", 
    "mcatnlo_7051" => "cmcatnlo_v5_7051_chain", 
    "mcatnlo_7055" => "cmcatnlo_v5_7055_chain", 
    "mcatnlo_7060" => "cmcatnlo_v5_7060_chain", 
    "mcatnlo_7061" => "cmcatnlo_v5_7061_chain", 
    "mcatnlo_7065" => "cmcatnlo_v5_7065_chain", 
    "mcatnlo_7070" => "cmcatnlo_v5_7070_chain", 
    "mcatnlo_7071" => "cmcatnlo_v5_7071_chain", 
    "mcatnlo_7075" => "cmcatnlo_v5_7075_chain", 
    "mcatnlo_7080" => "cmcatnlo_v5_7080_chain", 
    "mcatnlo_7081" => "cmcatnlo_v5_7081_chain", 
    "mcatnlo_7085" => "cmcatnlo_v5_7085_chain", 
    "mcatnlo_7090" => "cmcatnlo_v5_7090_chain", 
    "mcatnlo_7091" => "cmcatnlo_v5_7091_chain", 
    "mcatnlo_7095" => "cmcatnlo_v5_7095_chain", 
    "mcatnlo_7100" => "cmcatnlo_v5_7100_chain", 
    "mcatnlo_7101" => "cmcatnlo_v5_7101_chain", 
    "mcatnlo_7105" => "cmcatnlo_v5_7105_chain", 
    "mcatnlo_7110" => "cmcatnlo_v5_7110_chain", 
    "mcatnlo_7111" => "cmcatnlo_v5_7111_chain", 
    "mcatnlo_7115" => "cmcatnlo_v5_7115_chain", 
    "mcatnlo_7120" => "cmcatnlo_v5_7120_chain", 
    "mcatnlo_7121" => "cmcatnlo_v5_7121_chain", 
    "mcatnlo_7125" => "cmcatnlo_v5_7125_chain", 
    "mcatnlo_7130" => "cmcatnlo_v5_7130_chain", 
    "mcatnlo_7131" => "cmcatnlo_v5_7131_chain", 
    "mcatnlo_7135" => "cmcatnlo_v5_7135_chain", 
    "mcatnlo_7140" => "cmcatnlo_v5_7140_chain", 
    "mcatnlo_7141" => "cmcatnlo_v5_7141_chain", 
    "mcatnlo_7145" => "cmcatnlo_v5_7145_chain", 
    "mcatnlo_7150" => "cmcatnlo_v5_7150_chain", 
    "mcatnlo_7151" => "cmcatnlo_v5_7151_chain", 
    "mcatnlo_7155" => "cmcatnlo_v5_7155_chain", 
    "mcatnlo_7160" => "cmcatnlo_v5_7160_chain", 
    "mcatnlo_7161" => "cmcatnlo_v5_7161_chain", 
    "mcatnlo_7165" => "cmcatnlo_v5_7165_chain", 
    "mcatnlo_7170" => "cmcatnlo_v5_7170_chain", 
    "mcatnlo_7171" => "cmcatnlo_v5_7171_chain", 
    "mcatnlo_7175" => "cmcatnlo_v5_7175_chain", 
    "mcatnlo_7180" => "cmcatnlo_v5_7180_chain", 
    "mcatnlo_7181" => "cmcatnlo_v5_7181_chain", 
    "mcatnlo_7185" => "cmcatnlo_v5_7185_chain", 
    "mcatnlo_7190" => "cmcatnlo_v5_7190_chain", 
    "mcatnlo_7191" => "cmcatnlo_v5_7191_chain", 
    "mcatnlo_7195" => "cmcatnlo_v5_7195_chain", 
    "mcatnlo_7200" => "cmcatnlo_v5_7200_chain", 
    "mcatnlo_7201" => "cmcatnlo_v5_7201_chain", 
    "mcatnlo_7205" => "cmcatnlo_v5_7205_chain", 
    "mcatnlo_7210" => "cmcatnlo_v5_7210_chain", 
    "mcatnlo_7211" => "cmcatnlo_v5_7211_chain", 
    "mcatnlo_7215" => "cmcatnlo_v5_7215_chain", 
    "mcatnlo_7220" => "cmcatnlo_v5_7220_chain", 
    "mcatnlo_7221" => "cmcatnlo_v5_7221_chain", 
    "mcatnlo_7225" => "cmcatnlo_v5_7225_chain", 
    "mcatnlo_7230" => "cmcatnlo_v5_7230_chain", 
    "mcatnlo_7231" => "cmcatnlo_v5_7231_chain", 
    "mcatnlo_7235" => "cmcatnlo_v5_7235_chain", 
    "mcatnlo_7240" => "cmcatnlo_v5_7240_chain", 
    "mcatnlo_7241" => "cmcatnlo_v5_7241_chain", 
    "mcatnlo_7245" => "cmcatnlo_v5_7245_chain", 
    "mcatnlo_7250" => "cmcatnlo_v5_7250_chain", 
    "mcatnlo_7251" => "cmcatnlo_v5_7251_chain", 
    "mcatnlo_7255" => "cmcatnlo_v5_7255_chain", 
    "mcatnlo_7260" => "cmcatnlo_v5_7260_chain", 
    "mcatnlo_7261" => "cmcatnlo_v5_7261_chain", 
    "mcatnlo_7265" => "cmcatnlo_v5_7265_chain", 
    "mcatnlo_7270" => "cmcatnlo_v5_7270_chain", 
    "mcatnlo_7271" => "cmcatnlo_v5_7271_chain", 
    "mcatnlo_7275" => "cmcatnlo_v5_7275_chain", 
    "mcatnlo_7280" => "cmcatnlo_v5_7280_chain", 
    "mcatnlo_7281" => "cmcatnlo_v5_7281_chain", 
    "mcatnlo_7285" => "cmcatnlo_v5_7285_chain", 
    "mcatnlo_7290" => "cmcatnlo_v5_7290_chain", 
    "mcatnlo_7291" => "cmcatnlo_v5_7291_chain", 
    "mcatnlo_7295" => "cmcatnlo_v5_7295_chain", 
    "mcatnlo_7300" => "cmcatnlo_v5_7300_chain", 
    "mcatnlo_7301" => "cmcatnlo_v5_7301_chain", 
    "mcatnlo_7305" => "cmcatnlo_v5_7305_chain", 
    "mcatnlo_7310" => "cmcatnlo_v5_7310_chain", 
    "mcatnlo_7311" => "cmcatnlo_v5_7311_chain", 
    "mcatnlo_7315" => "cmcatnlo_v5_7315_chain", 
    "mcatnlo_7320" => "cmcatnlo_v5_7320_chain", 
    "mcatnlo_7321" => "cmcatnlo_v5_7321_chain", 
    "mcatnlo_7325" => "cmcatnlo_v5_7325_chain", 
    "mcatnlo_7330" => "cmcatnlo_v5_7330_chain", 
    "mcatnlo_7331" => "cmcatnlo_v5_7331_chain", 
    "mcatnlo_7335" => "cmcatnlo_v5_7335_chain", 
    "mcatnlo_7340" => "cmcatnlo_v5_7340_chain", 
    "mcatnlo_7341" => "cmcatnlo_v5_7341_chain", 
    "mcatnlo_7345" => "cmcatnlo_v5_7345_chain", 
    "mcatnlo_7350" => "cmcatnlo_v5_7350_chain", 
    "mcatnlo_7351" => "cmcatnlo_v5_7351_chain", 
    "mcatnlo_7355" => "cmcatnlo_v5_7355_chain", 
    "mcatnlo_7360" => "cmcatnlo_v5_7360_chain", 
    "mcatnlo_7361" => "cmcatnlo_v5_7361_chain", 
    "mcatnlo_7365" => "cmcatnlo_v5_7365_chain", 
    "mcatnlo_7370" => "cmcatnlo_v5_7370_chain", 
    "mcatnlo_7371" => "cmcatnlo_v5_7371_chain", 
    "mcatnlo_7375" => "cmcatnlo_v5_7375_chain", 
    "mcatnlo_7380" => "cmcatnlo_v5_7380_chain", 
    "mcatnlo_7381" => "cmcatnlo_v5_7381_chain", 
    "mcatnlo_7385" => "cmcatnlo_v5_7385_chain", 
    "mcatnlo_7390" => "cmcatnlo_v5_7390_chain", 
    "mcatnlo_7391" => "cmcatnlo_v5_7391_chain", 
    "mcatnlo_7395" => "cmcatnlo_v5_7395_chain", 
    "mcatnlo_7400" => "cmcatnlo_v5_7400_chain", 
    "mcatnlo_7401" => "cmcatnlo_v5_7401_chain", 
    "mcatnlo_7405" => "cmcatnlo_v5_7405_chain", 
#
    "sherpa_131" => "csherpa_131_chain",
    "sherpa_132" => "csherpa_132_chain",
    "sherpa_132_sys" => "csherpa_132_sys",
    "sherpa_133_sys" => "csherpa_133_sys",
    "sherpa_134_sys" => "csherpa_134_sys",
    "sherpa_135_sys" => "csherpa_135_sys",
    "sherpa_141_sys" => "csherpa_141_sys",
    "sherpa_150_sys" => "csherpa_150_sys",
    "sherpa_151_sys" => "csherpa_151_sys",
    "sherpa_152_sys" => "csherpa_152_sys"
);

my @lines;
print "srmLs -x $storage -c -p root \n";
@lines = `srmLs -x $storage -c -p root |sort`;
@lines = grep(s/\n//, @lines); 
for $i (@lines) {
    print "lines $i\n";
}


foreach $j (keys %jobs) {
    if ($opt_s && $opt_s ne $j) {
	print "$opt_s does not correspond to $j, skipping\n";
	next;
    }
    # $output = "$jobs{$j}".".root";
    $output = "$j".".root";
    $frag = $jobs{$j};
    @rootfiles = grep{$_ =~ $frag} @lines; 
    @rootfiles = grep{$_ =~ /\.root/} @rootfiles; 
    #    @rootfiles = grep(s/\n//, @rootfiles); 
    for $i (@rootfiles) {
	print "-> $i\n";
    }

    print "merging $jobs{$j} into $opt_o/$output\n";

    if ($#rootfiles == 0) {
	@rootfiles = grep(s/.*$user\/$rootdir\///, @rootfiles); 
	if ($opt_d) {
	    print "$srmcmd $storage/$rootfiles[0] $opt_o/$output \n";
	} else {
	    system("$srmcmd $storage/$rootfiles[0] $opt_o/$output");
	}	    
    } elsif ($#rootfiles > 0) {
	@rootfiles = grep(s/.*\/trivcat/$dcap/, @rootfiles); 
	@rootfiles = sort @rootfiles; 
	
	if (-e "$opt_o/$output") {unlink("$opt_o/$output"); }
	system("hadd $opt_o/$output @rootfiles");
    }
    
}

